apiVersion: v1
kind: Service
metadata:
  name: llm-runtime
  labels:
    app: llm-runtime
spec:
  type: {{ .Values.service.type }}
  selector:
    app: llm-runtime
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 11434
      protocol: TCP