apiVersion: v1
kind: Service
metadata:
  name: llm-api
  labels:
    app: llm-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: llm-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP